name: Install build dependencies
description: Installs JDK 17, hadolint, and spectral for Java app builds

runs:
  using: composite
  steps:
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install hadolint
      shell: bash
      run: |
        sudo wget -O /usr/local/bin/hadolint \
          "https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-Linux-x86_64"
        sudo chmod +x /usr/local/bin/hadolint

        hadolint --version
        which hadolint
      env:
        HADOLINT_VERSION: '2.10.0'

    - name: Install spectral JSON/YAML linter
      shell: bash
      run: npm install -g @stoplight/spectral-cli@6.4.0

    - name: Output ShellCheck info
      shell: bash
      run: |
        shellcheck --version
        which shellcheck
